'use client'

import { usePathname } from 'next/navigation'
import { useState } from 'react'

/**
 * Per-page toolbar with two actions:
 *   - "Copy markdown" — fetches the raw .md mirror and copies to clipboard.
 *   - "View as markdown" — direct link to the raw .md mirror.
 *
 * The raw mirrors are generated by scripts/generate-llms.mjs into
 * public/<path>.md, so /foo/bar resolves to /foo/bar.md.
 */
export default function LLMToolbar() {
  const pathname = usePathname() || '/'
  const [state, setState] = useState('idle') // idle | copied | error

  const mdPath = pathname === '/' ? '/index.md' : `${pathname.replace(/\/$/, '')}.md`

  async function copy() {
    try {
      const res = await fetch(mdPath)
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const text = await res.text()
      await navigator.clipboard.writeText(text)
      setState('copied')
      setTimeout(() => setState('idle'), 2000)
    } catch {
      setState('error')
      setTimeout(() => setState('idle'), 2000)
    }
  }

  return (
    <div
      style={{
        display: 'flex',
        gap: '0.5rem',
        marginBottom: '1.5rem',
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.8rem',
      }}
    >
      <button
        onClick={copy}
        style={{
          padding: '0.25rem 0.75rem',
          background: 'transparent',
          border: '1px solid var(--defcon5-fg-dim, #888)',
          borderRadius: '4px',
          color: 'var(--defcon5-fg, inherit)',
          cursor: 'pointer',
          font: 'inherit',
        }}
        aria-label="Copy this page as markdown for pasting into an LLM"
      >
        {state === 'copied' ? '✓ Copied' : state === 'error' ? '✗ Failed' : '📋 Copy for LLM'}
      </button>
      <a
        href={mdPath}
        style={{
          padding: '0.25rem 0.75rem',
          border: '1px solid var(--defcon5-fg-dim, #888)',
          borderRadius: '4px',
          color: 'var(--defcon5-fg, inherit)',
          textDecoration: 'none',
        }}
        aria-label="View this page as raw markdown"
      >
        View as .md
      </a>
    </div>
  )
}
