version: 2

project_name: squadron

builds:
  - id: squadron
    binary: squadron
    main: ./cmd/cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X squadron/cmd.Version={{.Version}}

archives:
  - id: squadron
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github-native

release:
  github:
    owner: mlund01
    name: squadron
