version: 2

project_name: squadron

builds:
  - id: squadron
    binary: squadron
    main: ./cmd/cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: squadron
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: mlund01
    name: squadron

homebrew_casks:
  - name: squadron
    repository:
      owner: mlund01
      name: homebrew-squadron
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/mlund01/squadron"
    description: "CLI for defining and running AI agents and multi-agent workflows"
    binaries:
      - squadron
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/squadron"]
          end
