version: 2

project_name: squadron

builds:
  - id: squadron
    binary: squadron
    main: ./cmd/cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: squadron
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: mlund01
    name: squadron

brews:
  - name: squadron
    repository:
      owner: mlund01
      name: squadron
      directory: Formula
    homepage: "https://github.com/mlund01/squadron"
    description: "CLI for defining and running AI agents and multi-agent workflows"
    license: "MIT"
    install: |
      bin.install "squadron"
    test: |
      system "#{bin}/squadron", "--help"
