services:
  squadron:
    build:
      context: .
      dockerfile: Dockerfile.debian
    volumes:
      - ./../workflows:/config
    command: ["serve", "--init", "-w", "--cc-port", "8080", "--no-browser"]
    ports:
      - "8080:8080"
