services:
  squadron:
    build:
      context: .
      dockerfile: Dockerfile.debian
    volumes:
      - ./../workflows:/config
      - squadron-data:/data/squadron
    command: ["serve", "-w", "--cc-port", "8080", "--no-browser"]
    ports:
      - "8080:8080"

volumes:
  squadron-data:
