package oauth

import (
	"context"
	"fmt"
	"sync"

	"github.com/mlund01/squadron-wire/protocol"

	"squadron/internal/browser"
)

// WSCaller is the minimum surface of wsbridge.Client that the
// WsbridgeCallbackSource needs. Accepting an interface keeps this package
// independent of wsbridge for tests and avoids an import cycle.
type WSCaller interface {
	SendRequest(env *protocol.Envelope) (*protocol.Envelope, error)
	// RegisterOAuthListener attaches a buffered channel to receive the
	// OAuth callback delivered over the WS bridge for the given state.
	// Returns a cancel function.
	RegisterOAuthListener(state string, ch chan<- WSCallback) func()
}

// WSCallback is the shape of the OAuth callback delivered by the WS bridge.
// Kept separate from CallbackParams so the oauth package does not depend on
// wsbridge types (wsbridge.OAuthCallback has the same fields).
type WSCallback struct {
	Code  string
	State string
	Error string
}

// WsbridgeCallbackSource implements CallbackSource by routing the OAuth
// callback through command center: the user's browser hits commander's
// public /oauth/callback URL, commander pushes the (code, state) pair back
// to this squadron over the WS bridge, and we deliver it to the login flow.
//
// This source is only useful when squadron is connected to a command center.
// The CLI `squadron mcp login` command (which runs as a separate process
// with no live bridge) always uses LoopbackCallbackSource.
type WsbridgeCallbackSource struct {
	client      WSCaller
	redirectURI string
	mcpName     string

	// AuthURLHook is called synchronously by Present with the authorization
	// URL. The default opens the user's default browser. UI-initiated flows
	// override this to ferry the URL out-of-band to the browser that started
	// the login (via window.open) instead of a server-side browser launch.
	AuthURLHook func(authURL string)

	mu     sync.Mutex
	state  string
	ch     chan WSCallback
	cancel func() // deregisters the listener; set in Present, cleared in Close
	once   sync.Once
}

// NewWsbridgeCallbackSource creates a source that uses the given redirect
// URI (typically cfg.CommandCenter.OAuthRedirectURI()) and delegates to
// client for WS-based callback delivery. Single-use — create one per login.
func NewWsbridgeCallbackSource(client WSCaller, mcpName, redirectURI string) *WsbridgeCallbackSource {
	return &WsbridgeCallbackSource{
		client:      client,
		redirectURI: redirectURI,
		mcpName:     mcpName,
		ch:          make(chan WSCallback, 1),
	}
}

// Prepare returns the configured redirect URI. There is no local server to
// start — commander serves the callback endpoint.
func (s *WsbridgeCallbackSource) Prepare(ctx context.Context) (string, error) {
	if s.redirectURI == "" {
		return "", fmt.Errorf("wsbridge oauth: empty redirect URI (command_center.host not configured?)")
	}
	if s.client == nil {
		return "", fmt.Errorf("wsbridge oauth: no ws client available")
	}
	return s.redirectURI, nil
}

// SetState records the OAuth state value generated by the login flow so
// Present can register the bridge listener under the matching key.
func (s *WsbridgeCallbackSource) SetState(state string) {
	s.mu.Lock()
	s.state = state
	s.mu.Unlock()
}

// Present registers a bridge listener keyed by state, asks commander to
// reserve the flow, then delivers the authorization URL (default: open the
// user's browser). The OAuth IdP later redirects the user to commander's
// /oauth/callback, which forwards the params back to our listener.
func (s *WsbridgeCallbackSource) Present(ctx context.Context, authURL string) error {
	s.mu.Lock()
	state := s.state
	s.mu.Unlock()
	if state == "" {
		return fmt.Errorf("wsbridge oauth: SetState must be called before Present")
	}

	// Register the listener FIRST so we never race with an ultra-fast IdP.
	cancel := s.client.RegisterOAuthListener(state, s.ch)
	s.mu.Lock()
	s.cancel = cancel
	s.mu.Unlock()

	// Reserve the flow with commander.
	env, err := protocol.NewRequest(protocol.TypeOAuthRegisterFlow, &protocol.OAuthRegisterFlowPayload{
		State:   state,
		McpName: s.mcpName,
	})
	if err != nil {
		return fmt.Errorf("wsbridge oauth: build register request: %w", err)
	}
	resp, err := s.client.SendRequest(env)
	if err != nil {
		return fmt.Errorf("wsbridge oauth: registering flow with commander: %w", err)
	}
	if resp.Type == protocol.TypeError {
		var perr protocol.ErrorPayload
		_ = protocol.DecodePayload(resp, &perr)
		return fmt.Errorf("wsbridge oauth: commander rejected flow registration: %s", perr.Message)
	}
	var ack protocol.OAuthRegisterFlowAckPayload
	if err := protocol.DecodePayload(resp, &ack); err != nil {
		return fmt.Errorf("wsbridge oauth: decoding register ack: %w", err)
	}
	if !ack.Accepted {
		return fmt.Errorf("wsbridge oauth: commander rejected flow: %s", ack.Reason)
	}

	// Deliver the auth URL. Default: open the user's default browser (this
	// is what the CLI wants, same as loopback). UI-initiated flows swap the
	// hook to ferry the URL back to the browser that requested the login.
	hook := s.AuthURLHook
	if hook == nil {
		hook = func(u string) {
			fmt.Printf("Opening browser to authorize...\n")
			fmt.Printf("If it does not open, visit:\n  %s\n", u)
			browser.Open(u)
		}
	}
	hook(authURL)
	return nil
}

// Wait blocks until commander delivers a callback for our state.
func (s *WsbridgeCallbackSource) Wait(ctx context.Context) (CallbackParams, error) {
	select {
	case cb := <-s.ch:
		if cb.Error != "" {
			return CallbackParams{}, fmt.Errorf("authorization server returned error: %s", cb.Error)
		}
		if cb.Code == "" {
			return CallbackParams{}, fmt.Errorf("authorization server redirected without code")
		}
		return CallbackParams{Code: cb.Code, State: cb.State}, nil
	case <-ctx.Done():
		return CallbackParams{}, ctx.Err()
	}
}

// Close deregisters the bridge listener.
func (s *WsbridgeCallbackSource) Close() error {
	s.once.Do(func() {
		s.mu.Lock()
		cancel := s.cancel
		s.cancel = nil
		s.mu.Unlock()
		if cancel != nil {
			cancel()
		}
	})
	return nil
}
