# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadron < Formula
  desc "CLI for defining and running AI agents and multi-agent workflows"
  homepage "https://github.com/mlund01/squadron"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.5/squadron_darwin_amd64.tar.gz"
      sha256 "e9f60adb867242be8c52b6566e8566bbb02b37c2b7895b2d118c75f38bdecec9"

      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.5/squadron_darwin_arm64.tar.gz"
      sha256 "2c155a40b6e8ca8e855cda41cddebc08b0f150e4f52e899c7325294d3e982389"

      def install
        bin.install "squadron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.5/squadron_linux_amd64.tar.gz"
      sha256 "ab142f2574e257cba3e28bb1066fac91c6b4522a77d250ff8d927d4e63f44c3f"
      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mlund01/squadron/releases/download/v0.0.5/squadron_linux_arm64.tar.gz"
      sha256 "05f82d1cd12e2368a65c845d75941ea4f3556815486bfb864948181059ce2c80"
      def install
        bin.install "squadron"
      end
    end
  end

  test do
    system "#{bin}/squadron", "--help"
  end
end
